// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Jun 2018 15:06:16 WAT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "nanovg.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

