// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Jun 2018 15:06:16 WAT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nvg

/*
#include "nanovg.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// _PI as defined in src/nanovg.h:26
	_PI = 3.14159265358979323846264338327
)

// Winding as declared in src/nanovg.h:56
type Winding int32

// Winding enumeration from src/nanovg.h:56
const (
	_CCW = 1
	_CW  = 2
)

// Solidity as declared in src/nanovg.h:61
type Solidity int32

// Solidity enumeration from src/nanovg.h:61
const (
	_SOLID = 1
	_HOLE  = 2
)

// LineCap as declared in src/nanovg.h:66
type LineCap int32

// LineCap enumeration from src/nanovg.h:66
const (
	_BUTT   = iota
	_ROUND  = 1
	_SQUARE = 2
	_BEVEL  = 3
	_MITER  = 4
)

// Align as declared in src/nanovg.h:74
type Align int32

// Align enumeration from src/nanovg.h:74
const (
	_ALIGN_LEFT     = 1 << 0
	_ALIGN_CENTER   = 1 << 1
	_ALIGN_RIGHT    = 1 << 2
	_ALIGN_TOP      = 1 << 3
	_ALIGN_MIDDLE   = 1 << 4
	_ALIGN_BOTTOM   = 1 << 5
	_ALIGN_BASELINE = 1 << 6
)

// BlendFactor as declared in src/nanovg.h:86
type BlendFactor int32

// BlendFactor enumeration from src/nanovg.h:86
const (
	_ZERO                = 1 << 0
	_ONE                 = 1 << 1
	_SRC_COLOR           = 1 << 2
	_ONE_MINUS_SRC_COLOR = 1 << 3
	_DST_COLOR           = 1 << 4
	_ONE_MINUS_DST_COLOR = 1 << 5
	_SRC_ALPHA           = 1 << 6
	_ONE_MINUS_SRC_ALPHA = 1 << 7
	_DST_ALPHA           = 1 << 8
	_ONE_MINUS_DST_ALPHA = 1 << 9
	_SRC_ALPHA_SATURATE  = 1 << 10
)

// CompositeOperation as declared in src/nanovg.h:100
type CompositeOperation int32

// CompositeOperation enumeration from src/nanovg.h:100
const (
	_SOURCE_OVER      = iota
	_SOURCE_IN        = 1
	_SOURCE_OUT       = 2
	_ATOP             = 3
	_DESTINATION_OVER = 4
	_DESTINATION_IN   = 5
	_DESTINATION_OUT  = 6
	_DESTINATION_ATOP = 7
	_LIGHTER          = 8
	_COPY             = 9
	_XOR              = 10
)

// ImageFlags as declared in src/nanovg.h:138
type ImageFlags int32

// ImageFlags enumeration from src/nanovg.h:138
const (
	_IMAGE_GENERATE_MIPMAPS = 1 << 0
	_IMAGE_REPEATX          = 1 << 1
	_IMAGE_REPEATY          = 1 << 2
	_IMAGE_FLIPY            = 1 << 3
	_IMAGE_PREMULTIPLIED    = 1 << 4
	_IMAGE_NEAREST          = 1 << 5
)

// Texture as declared in src/nanovg.h:618
type Texture int32

// Texture enumeration from src/nanovg.h:618
const (
	_TEXTURE_ALPHA = 0x01
	_TEXTURE_RGBA  = 0x02
)
