// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Jun 2018 15:06:16 WAT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package nanovg provides Go bindings for nanovg.h — is small antialiased vector graphics rendering library for OpenGL.
*/
package nvg
