// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Jun 2018 15:06:16 WAT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nvg

/*
#include "nanovg.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Context as declared in src/nanovg.h:33
type Context C.NVGcontext

// Color as declared in src/nanovg.h:43
type Color struct {
	refab19561b    *C.NVGcolor
	allocsab19561b interface{}
}

// Paint as declared in src/nanovg.h:54
type Paint struct {
	Xform          [6]float32
	Extent         [2]float32
	Radius         float32
	Feather        float32
	InnerColor     Color
	OuterColor     Color
	Image          int32
	ref9a359ae5    *C.NVGpaint
	allocs9a359ae5 interface{}
}

// CompositeOperationState as declared in src/nanovg.h:120
type CompositeOperationState struct {
	SrcRGB         int32
	DstRGB         int32
	SrcAlpha       int32
	DstAlpha       int32
	ref1ac74feb    *C.NVGcompositeOperationState
	allocs1ac74feb interface{}
}

// GlyphPosition as declared in src/nanovg.h:127
type GlyphPosition struct {
	Str            string
	X              float32
	Minx           float32
	Maxx           float32
	ref7a6d48e2    *C.NVGglyphPosition
	allocs7a6d48e2 interface{}
}

// TextRow as declared in src/nanovg.h:136
type TextRow struct {
	Start          string
	End            string
	Next           string
	Width          float32
	Minx           float32
	Maxx           float32
	ref6f343350    *C.NVGtextRow
	allocs6f343350 interface{}
}

// Scissor as declared in src/nanovg.h:627
type Scissor struct {
	Xform          [6]float32
	Extent         [2]float32
	reff578b010    *C.NVGscissor
	allocsf578b010 interface{}
}

// Vertex as declared in src/nanovg.h:632
type Vertex struct {
	X              float32
	Y              float32
	U              float32
	V              float32
	refba8fa51b    *C.NVGvertex
	allocsba8fa51b interface{}
}

// Path as declared in src/nanovg.h:646
type Path struct {
	First          int32
	Count          int32
	Closed         byte
	Nbevel         int32
	Fill           []Vertex
	Nfill          int32
	Stroke         []Vertex
	Nstroke        int32
	Winding        int32
	Convex         int32
	ref934ceafa    *C.NVGpath
	allocs934ceafa interface{}
}

// Params as declared in src/nanovg.h:664
type Params struct {
	UserPtr              unsafe.Pointer
	EdgeAntiAlias        int32
	RenderCreate         *func(uptr unsafe.Pointer) int32
	RenderCreateTexture  *func(uptr unsafe.Pointer, _type int32, w int32, h int32, imageFlags int32, data string) int32
	RenderDeleteTexture  *func(uptr unsafe.Pointer, image int32) int32
	RenderUpdateTexture  *func(uptr unsafe.Pointer, image int32, x int32, y int32, w int32, h int32, data string) int32
	RenderGetTextureSize *func(uptr unsafe.Pointer, image int32, w []int32, h []int32) int32
	RenderViewport       *func(uptr unsafe.Pointer, width float32, height float32, devicePixelRatio float32)
	RenderCancel         *func(uptr unsafe.Pointer)
	RenderFlush          *func(uptr unsafe.Pointer)
	RenderFill           *func(uptr unsafe.Pointer, paint []Paint, compositeOperation CompositeOperationState, scissor []Scissor, fringe float32, bounds []float32, paths []Path, npaths int32)
	RenderStroke         *func(uptr unsafe.Pointer, paint []Paint, compositeOperation CompositeOperationState, scissor []Scissor, fringe float32, strokeWidth float32, paths []Path, npaths int32)
	RenderTriangles      *func(uptr unsafe.Pointer, paint []Paint, compositeOperation CompositeOperationState, scissor []Scissor, verts []Vertex, nverts int32)
	RenderDelete         *func(uptr unsafe.Pointer)
	refdcb0d2dd          *C.NVGparams
	allocsdcb0d2dd       interface{}
}
